from os.path import join, dirname


OUTPUT_DIR = "results"
TEMP_DIR = "temp"
LOGS_DIR = "logs"
BENCHMARK_DIR = "benchmarks"

# {sm: {"target_path": "", "qry_path": ""}}

WD = "/project/logsdon_shared/projects/HPRC/CenMAP-R1vR2/results/"
GLOB_ASM = join(
    WD, "{release}/results/{release}/2-concat_asm/{sm}-asm-renamed-reort.fa"
)
WCS = glob_wildcards(GLOB_ASM)
SAMPLES = [sm for sm, release in zip(WCS.sm, WCS.release) if release == "R2"]
FASTA = {
    sm: {
        "target": GLOB_ASM.format(release="R2", sm=sm),
        "query": GLOB_ASM.format(release="R1", sm=sm),
    }
    for sm in SAMPLES
}
DST = [
    1_000,
]


rule alignment:
    input:
        ref=lambda wc: FASTA[wc.sm]["target"],
        query=lambda wc: FASTA[wc.sm]["query"],
    output:
        aln=os.path.join(TEMP_DIR, "{sm}.bam"),
    log:
        os.path.join(LOGS_DIR, "alignment_{sm}.log"),
    benchmark:
        os.path.join(BENCHMARK_DIR, "alignment_{sm}.tsv")
    resources:
        mem=config.get("aln_mem", "12GB"),
    conda:
        "../asm-to-reference-alignment/workflow/envs/env.yml"
    threads: config.get("aln_threads", 4)
    params:
        mm2_opts=config.get("mm2_opts", "-x asm5 --secondary=no -K 8G"),
    shell:
        """
        {{ minimap2 -t {threads} -a --eqx --cs \
            {params.mm2_opts} \
            {input.ref} {input.query} \
            | samtools view -F 4 -b -;}} \
            > {output.aln} 2> {log}
        """


rule bam_to_paf:
    input:
        aln=rules.alignment.output.aln,
    output:
        paf=os.path.join(OUTPUT_DIR, "{sm}.paf"),
    log:
        os.path.join(LOGS_DIR, "bam_to_paf_{sm}.log"),
    conda:
        "../asm-to-reference-alignment/workflow/envs/env.yml"
    shell:
        """
        {{ samtools view -h {input.aln} | paftools.js sam2paf - ;}} > {output.paf} 2> {log}
        """


rule liftover_cdr_bed:
    input:
        bed="/project/logsdon_shared/projects/HPRC/CenMAP-R1vR2/results/R2/results/R2/8-cdr_finder/bed/all_cdrs.bed",
        paf=rules.bam_to_paf.output,
    output:
        bed=os.path.join(OUTPUT_DIR, "{sm}_cdr_intersected.bed"),
    params:
        bp_merge=150_000,
    shell:
        """
        impg query \
        -p {input.paf} \
        -b <(sort -k1,1 -k2,2n {input.bed} | \
            grep "{wildcards.sm}" | \
            bedtools merge -i - -d {params.bp_merge} | \
            awk -v OFS="\\t" '{{
                match($1, "^(.+):", chroms);
                print chroms[1], $2, $3
            }}') > {output.bed}
        """


rule determine_n_breaks:
    input:
        fai_r1="/project/logsdon_shared/projects/HPRC/CenMAP-R1vR2/results/R1/results/R1/2-concat_asm/{sm}-asm-renamed-reort.fa.fai",
        bed_r1_complete="/project/logsdon_shared/projects/HPRC/CenMAP-R1vR2/results/R1/results/R1/final/bed/{sm}_complete_correct_cens.bed",
        bed_r2_complete="/project/logsdon_shared/projects/HPRC/CenMAP-R1vR2/results/R2/results/R2/final/bed/{sm}_complete_correct_cens.bed",
        bed_cdr_ovl=rules.liftover_cdr_bed.output,
    output:
        tsv=join(OUTPUT_DIR, "{sm}_{dst}.tsv"),
    params:
        script="determine_counts.py",
    shell:
        """
        python {params.script} {input.bed_cdr_ovl} {input.fai_r1} {input.bed_r1_complete} {input.bed_r2_complete} {output} {wildcards.dst}
        """


rule aggregate_breaks:
    input:
        expand(rules.determine_n_breaks.output, sm=SAMPLES, dst="{dst}"),
    output:
        tsv=join(OUTPUT_DIR, "all_{dst}.tsv"),
    shell:
        """
        cat {input} > {output}
        """


rule plot_summarize_breaks:
    input:
        rules.aggregate_breaks.output,
    output:
        join(OUTPUT_DIR, "{dst}", "cdr_breaks_summary.png"),
        join(OUTPUT_DIR, "{dst}", "cdr_breaks_summary.tsv"),
    params:
        script="summarize_counts.py",
        output_dir=lambda wc, output: dirname(output[0]),
    shell:
        """
        python {params.script} {input} {params.output_dir}
        """


rule all:
    input:
        expand(rules.liftover_cdr_bed.output, sm=SAMPLES),
        expand(rules.determine_n_breaks.output, sm=SAMPLES, dst=DST),
        expand(rules.plot_summarize_breaks.output, dst=DST),
    default_target: True
